development:
  adapter: postgresql
  encoding: unicode
  database: blog_app2_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: blog_app2_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost